# Generated by Django 5.2.5 on 2025-08-11 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='full_name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
