# Generated by Django 5.2.5 on 2025-08-10 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customUserAuth', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuserauthmodel',
            name='gender',
        ),
    ]
