# Generated by Django 5.2.5 on 2025-08-10 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customUserAuth', '0002_remove_customuserauthmodel_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuserauthmodel',
            name='user_types',
            field=models.CharField(choices=[('Admin', 'Admin'), ('HR', 'HR'), ('Employee', 'Employee')], max_length=10, null=True),
        ),
    ]
